#!/bin/bash

# NCBI: http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/
# EBI: http://www.ebi.ac.uk/ena/submit/read-xml-format-1-5

# download the xsd schema from NCBI's code repository
curl -o SRA.submission.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.submission.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.sample.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.sample.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.study.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.study.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.experiment.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.experiment.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.run.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.run.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.analysis.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.analysis.xsd?view=co&content-type=text%2Fplain' ;
curl -o SRA.common.xsd 'http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5d/SRA.common.xsd?view=co&content-type=text%2Fplain' ;

# correct the schema locations
for xsd in *.xsd; do
    perl -p -i -e 's{http://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/sra/doc/SRA_1-5/(SRA\.\w+\.xsd)\?view=co}{$1}' $xsd
done

# create the *.go files
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.analysis.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.common.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.experiment.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.run.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.sample.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.study.xsd"
xsd-makepkg -basepath=bitbucket.org/idas/go-sra-schemas -gofmt=true -local=true -uri="SRA.submission.xsd"

# I had to add the following line to all the autogenerated go files
#       type XsdtString struct{ string }
# Not sure if this is a bug or not...

for gofile in $(find . -name "*.go" -print); do
    perl -p -i -e 'if ($. == 11) { print "type XsdtString struct{ string }" } else { print $_ }' $gofile
done
